version: '3'
services:
  map-downloader:
    image: tobara/map-tiles-downloader
    ports:
      - 8081:8080
    restart: unless-stopped
    volumes:
      # Mount location for downloaded map tiles
      - ./output:/app/output